version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.12.2"
      TYPE: "FORGE"
      FORGE_VERSION: "14.23.5.2854"
      REMOVE_OLD_MODS: TRUE
      MEMORY: "4G"
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft/data/:/data
      - ./minecraft/mods/:/mods
      - ./minecraft/Flan/:/Flan
